server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/students,/api/students/**

            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses,/api/courses/**

            - id: enrollment-service
              uri: lb://enrollment-service
              predicates:
                - Path=/api/enrollments,/api/enrollments/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
